In [1]:
import numpy as np

In [ ]:
# Create a NumPy array 'arr' of integers from 0 to 5 and print its data type
# ANSWER:-
arr = np.arange(6)
print("array:", arr)
print("Data type:", arr.dtype)

array: [0 1 2 3 4 5]
Data type: int64


In [ ]:
# Given a NumPy array 'arr', check if its data type is float64?
# arr = np.array([1.5, 2.6, 3.7])
# ANSWER:-
arr = np.array([1.5, 2.6, 3.7])
is_float64 = arr.dtype == np.float64
print(is_float64)

True


In [ ]:
#  Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers?
# ANSWER:-
arr = np.array([1+2j, 3+4j, 5+6j], dtype= np.complex128)
print("array:", arr)
print("data type:", arr.dtype)

array: [1.+2.j 3.+4.j 5.+6.j]
data type: complex128


In [ ]:
#  Convert an existing NumPy array 'arr' of integers to float32 data type?
# ANSWER:-
arr = np.array([1, 2, 3, 4, 5], dtype=np.float32)
print("array:", arr)
print("data type:", arr.dtype)

array: [1. 2. 3. 4. 5.]
data type: float32


In [ ]:
#  Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
# ANSWER:-
arr = np.array([1.123456789, 2.987654321], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print("array:", arr_float32)
print("data type:", arr_float32.dtype)

array: [1.1234568 2.9876542]
data type: float32


In [ ]:
# Write a funcion array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
# ANSWER:-
def array_attributes(arr):
  return {
      'shape': arr.shape,
      'size': arr.size,
      'data type': arr.dtype
  }

test_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_attributes(test_arr))

{'shape': (2, 3), 'size': 6, 'data type': dtype('int64')}


In [ ]:
#  Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
# ANSWER:-
def array_dimension(arr):
  return arr.ndim

arr1d = np.array([1, 2, 3])
arr2d =np.array([[1, 2], [3, 4]])
arr3d = np.arange(8).reshape(2, 2, 2)
print(array_dimension(arr1d))
print(array_dimension(arr2d))
print(array_dimension(arr3d))

1
2
3


In [ ]:
# Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
# ANSWER:-
def item_size_info(arr):
  return {
      'item size': arr.itemsize,
      'total size': arr.nbytes
  }
test_arr = np.array([1, 2, 3, 4], dtype=np.int32)
info = item_size_info(test_arr)
print(info)

{'item size': 4, 'total size': 16}


In [ ]:
# Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
# ANSWER:-
def array_strides(arr):
  return arr.strides
test_arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(test_arr)
print(strides)

(24, 8)


In [ ]:
# Design a function shape_strides_relationship that takes a NumPy array as input and returns the shape and strides of the array.
# ANSWER:-
def  shape_strides_relationship(arr):
  return{
      'shape': arr.shape,
      'strides': arr.strides
  }
test_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
result = shape_strides_relationship(test_arr)
print(result)

{'shape': (2, 4), 'strides': (32, 8)}


In [ ]:
# Create a function 'create_zeros_array' that takes an integer 'n' as input and returns a NumPy array of zeros with 'n' elements.
# ANSWER:-
def create_zeros_array(n):
  return np.zeros(n)
zeros = create_zeros_array(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [ ]:
# Write a function 'create_ones_matrix' that takes integers 'rows' and 'cols' as inputs and generates a 2D NumPy array filled with ones of size 'rows x cols'.
# ANSWER:-
def create_ones_matrix(rows, cols):
  return np.ones((rows, cols))

ones = create_ones_matrix(3, 4)
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Write  a function 'generate_range_array' that takes three integers start , stop and step as arguments and creates a NumPy array with a range starting from 'start', ending at stop(exclusive), and with the specified 'step'.
# ANSWER:-
def generate_range_array(start, stop, step):
  return np.arange(start, stop, step)

arr = generate_range_array(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [ ]:
# Design a function 'generate_linear_space' that takes two floats 'start', 'stop', and an integer 'num' as arguments and generates a NumPy array with num equally spaced values between 'start' and 'stop' (inclusive).
# ANSWER:-
def generate_linear_space(start, stop, num):
  return np.linspace(start, stop, num)

arr = generate_linear_space(0, 10, 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
# Create a function'create_identity_matrix' that takes an integer 'n' as input and generates a square identity matrix of size 'n x n' using 'numpy.eye'.
# ANSWER:-
def create_identity_matrix(n):
  return np.eye(n)

identity = create_identity_matrix(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Write a function that takes a python list and converts it into a NumPy array.
# ANSWER:-
py_list = [1, 2, 3, 4, 5]
np_arr = np.array(py_list)
print(np_arr)
print(np_arr.dtype)

[1 2 3 4 5]
int64


In [ ]:
# Create a NumPy array and demostrate the use of 'numpy.view' to create a new array object with the same data.
# ANSWER:-
original = np.array([1.5, 2.6, 3.7])
view = original.view()
print(np.shares_memory(original, view))

True


In [ ]:
# Write a function that takes two NumPy arrays and concatenates them along a specified axis.
# ANSWER:-
def concatenates_arrays(arr1, arr2, axis=0):
  return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = concatenates_arrays(arr1, arr2)
print(result)

[1 2 3 4 5 6]


In [ ]:
# Create two NumPy arrays with different shapes and concatenate them horizontally usinng 'numpy.concatenate'.
# ANSWER:-
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
h_concat = np.concatenate((arr1, arr2), axis=1)
print(h_concat)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Write a function that vertically stacks multiple NumPy arrays given as a list.
# ANSWER:-
def vertically_stack(arr_list):
  return np.vstack(arr_list)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked = vertically_stack([arr1, arr2])
print(stacked)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Write a python function using NumPy to create an array of integers within a apecified range(inclusive) with a given step size.
# ANSWER:-
def range_with_step(start, end, step):
  return np.arange(start, end + 1, step)

result = range_with_step(0, 20, 3)
print(result)

[ 0  3  6  9 12 15 18]


In [ ]:
# Write a python using NumPy to generate an array of 10 equally spaced values between 0 and 1(inclusive).
# ANSWER:-
def equally_spaced_values(start, end, num):
  return np.linspace(start, end, num)

result = equally_spaced_values(0, 1, 10)
print(result)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
# Write a python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000(inclusive).
# ANSWER:-
def log_spaced(start, end, num):
  return np.logspace(np.log10(start), np.log10(end), num)

result = log_spaced(1, 1000, 5)
print(result)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
# Create a pandas DataFrame using a NumPy array that contains 5 rows and 3 coloumns, where the values are random integers between 1 and 100.
# ANSWER:-
import pandas as pd

arr = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(arr, columns=['col1', 'col2', 'col3'])
print(df)

   col1  col2  col3
0    87    29    13
1    99     7    10
2    38    55    46
3    73    71    76
4    56    64     1


In [ ]:
# Write a function that takes a pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the pandas DataFrame.
# ANSWER:-
def replace_negatives(df, column_name):
  df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
  return df

test_df = pd.DataFrame({'A': [1, -2, 3, -4]})
test_df = replace_negatives(test_df, 'A')
print(test_df)

   A
0  1
1  0
2  3
3  0


In [ ]:
# Access the 3rd element from the given NumPy array. "arr = np.array([10, 20, 30, 40, 50])"
# ANSWER:-
arr = np.array([10, 20, 30, 40, 50])
element = arr[2]
print(element)

30


In [ ]:
# Retreive the element at index (1, 2) from the 2D NumPy array.
# ANSWER:-
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = arr_2d[1, 2]
print(element)

6


In [ ]:
# Using boolean indexing, extract elements greater than 5 from the given NumPy array.
# ANSWER:-
arr = np.array([3, 8, 2, 10, 5, 7])
result = arr[arr > 5]
print(result)

[ 8 10  7]


In [ ]:
# Perform basic slicing to extract elements from index 2 to 5(inclusive) form the given NumPy array.
# ANSWER:-
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
result = arr[2:6]
print(result)

[3 4 5 6]


In [ ]:
# Slice the 2D NumPy array to extract the sub-array '[[2, 3], [5, 6]]' from the given array.
# ANSWER:-
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_arr = arr_2d[0:2, 1:3]
print(sub_arr)

[[2 3]
 [5 6]]


In [ ]:
# Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
# ANSWER:-
def extract_specific_order(arr_2d, indices_arr):
  return arr_2d[indices_arr[:, 0], indices_arr[:, 1]]

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 1], [1, 2], [2, 0]])
result = extract_specific_order(arr_2d, indices)
print(result)

[2 6 7]


In [ ]:
# Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
# ANSWER:-
def filter_by_threashold(arr, threshold):
  return arr[arr > threshold]

arr = np.array([3, 8, 2, 10, 5, 7])
result = filter_by_threashold(arr, 5)
print(result)

[ 8 10  7]


In [ ]:
# Develop a NumPy function that extracts specific elements from 3D array using indicies provided in three separate arrays for each dimension.
# ANSWER:-
def extract_3d_by_indices(arr_3d, indices_x, indices_y, indices_z):
  return arr_3d[indices_x, indices_y, indices_z]

arr_3d = np.arange(24).reshape(2, 3, 4)
ix = np.array([0, 1, 0])
iy = np.array([1, 2, 0])
iz = np.array([2, 1, 3])
result = extract_3d_by_indices(arr_3d, ix, iy, iz)
print(result)

[ 6 21  3]


In [ ]:
# Write a NumPy function that returns elements from am array where both two conditions are satisfied usinf boolean indexing.
# ANSWER:-
def filter_dual_conditions(arr, cond1_min, cond1_max, cond2_val):
  return arr[(arr >= cond1_min) & (arr <= cond1_max)]

arr = np.array([5, 10, 15, 20, 25, 30])
result = filter_dual_conditions(arr, 10, 25, None)
print(result)

[10 15 20 25]


In [ ]:
# Create a NumPy function that extracts elements from a 2D array using row and coloumn indices provided in separate arrays.
# ANSWER:-
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
rows = np.array([0, 1, 2])
cols = np.array([1, 2, 3])
result = arr_2d[rows, cols]
print(result)

[ 2  7 12]


In [ ]:
# Given an array arr of shape (3, 3), add a scalar value of 5 each element using NumPy broadcasting.
# ANSWER:-
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = arr+5
print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
# Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4).Multiply each row of arr2 by the corresponding element in arr1 using numpy broadcasting.
# ANSWER:-
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[1, 2, 3, 4]])
result = arr1*arr2
print(result)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]]


In [ ]:
# Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
# ANSWER:-
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.ones((4, 3))
result = arr1.T+arr2
print(result)

[[2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]]


In [ ]:
# Consider two arrays arr1 of shape(3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
# ANSWER:-
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([4, 5, 6])
result = arr1+arr2
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
# Given arrays arr1 of shape (2, 3) and arr2 of shape(2, 2). perform multiplication using NumPy broadcasting. Handle the shape inompatibility.
# ANSWER:-
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1, 2], [3, 4]])
arr2_reshaped = arr2[:, :, np.newaxis]
result = arr1*arr2_reshaped
print(result)

[[[ 1  2  3]
  [ 8 10 12]]

 [[ 3  6  9]
  [16 20 24]]]


In [ ]:
# Calculate coloumn-wise mean for the given array: 'arr = np.array([[1, 2, 3], [4, 5, 6]])'
# ANSWER:-
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_means = np.mean(arr, axis=0)
print(column_means)

[2.5 3.5 4.5]


In [ ]:
# Find maximum value in each row of the given array: 'arr = np.array([[1, 2, 3], [4, 5, 6]])'
# ANSWER:-
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_values = np.max(arr, axis=1)
print(max_values)

[3 6]


In [ ]:
# For the given array, find indices of maximum value in each column. 'arr = np.array([[1, 2, 3], [4, 5, 6]])'
# ANSWER:-
arr = np.array([[1, 2, 3], [4, 5, 6]])
col_max_indices = np.argmax(arr, axis=0)
print(col_max_indices)

[1 1 1]


In [ ]:
# For the given array, apply custom function to calculate moving sum along rows. 'arr = np.array([[1, 2, 3], [4, 5, 6]])'
# ANSWER:-
def moving_sum(arr, window_size=2):
  result = []
  for i in range(arr.shape[0]):
    row_sums = np.convolve(arr[i], np.ones(window_size), mode='valid')
    result.append(row_sums)
  return np.array(result)
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = moving_sum(arr, window_size=2)
print(result)

[[ 3.  5.]
 [ 9. 11.]]


In [ ]:
# In the given array, check if all elements in each column are even.:'arr = np.array([[2, 4, 6], [3, 5, 7]])'
# ANSWER:-
def check_even_columns(arr):
  return np.all(arr % 2 == 0, axis=0)

arr = np.array([[2, 4, 6], [3, 5, 7]])
result = check_even_columns(arr)
print(result)

[False False False]


In [ ]:
# Given a NumPy array arr, reshape it into a matrix of dimensions 'm' rows and 'n' columns. Return the reshaped matrix.
# ANSWER:-
def reshape_array(arr, m, n):
  return arr.reshape(m, n)

original = np.array([1, 2, 3, 4, 5, 6])
reshaped = reshape_array(original, 2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
# create a function that takes a matrix as input and  return the flattend array.
# ANSWER:-
def flatten_matrix(matrix):
  return matrix.flatten()

matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened = flatten_matrix(matrix)
print(flattened)

[1 2 3 4 5 6]


In [ ]:
# write a function that concatenates two given arrays along a specified axis.
# ANSWER:-
def concat_arrays(arr1, arr2, axis=0):
  return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result = concat_arrays(arr1, arr2, axis=1)
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# create a function that spilts an array into multiple sub-arrays along a specified axis.
# ANSWER:-
def split_array(arr, indices_or_sections, axis=0):
  return np.split(arr, indices_or_sections, axis=axis)
arr = np.array([1, 2, 3, 4, 5, 6])
result = split_array(arr, [2, 4], axis=0)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# Write a function that inserts and then deletes elements from a given array at specified indices.
# ANSWER:-
original = np.array([1, 2, 3, 4, 5])
arr_inserted = np.insert(original, [2, 4], [10, 11])
arr_deleted = np.delete(arr_inserted, [1, 3])
print(original)
print(arr_inserted)
print(arr_deleted)

[1 2 3 4 5]
[ 1  2 10  3  4 11  5]
[ 1 10  4 11  5]


In [ ]:
# create a NumPy array 'arr1' with random integers and another array 'arr2' with integers from 1 to 10. perform element-wise addition between 'arr1'and 'arr2'.
# ANSWER:-
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 3, 4, 5])
result = arr1+arr2
print(result)

[ 2  4  6  8 10]


In [ ]:
# Generate a NumPy array 'arr1' with sequential integers from 10 to 1 and another array 'arr2' with integers from 1 to 10. subtract 'arr2' from 'arr1' element-wise.
# ANSWER:-
arr1 = np.array([10, 9, 8, 7, 6])
arr2 = np.array([1, 2, 3, 4, 5])
result = arr1-arr2
print(result)

[9 7 5 3 1]


In [ ]:
# Create a NumPy array 'arr1' with random integers and another array 'arr2' with integers from 1 to 5. perform element-wise multiplication between 'arr1' and 'arr2'.
# ANSWER:-
arr1 = np.array([2, 3, 4, 5, 6])
arr2 = np.array([1, 2, 3, 4, 5])
result = arr1*arr2
print(result)

[ 2  6 12 20 30]


In [ ]:
# Generate a NumPy array 'arr1' with even integers from 2 to 10 and another array 'arr2' with integers from 1 to 5. perform element-wise division of 'arr1'by'arr2'.
# ANSWER:-
arr1 = np.array([2, 4, 6, 8, 10])
arr2 = np.array([1, 2, 3, 4, 5])
result = arr1/arr2
print(result)

[2. 2. 2. 2. 2.]


In [ ]:
# Create a NumPy array 'arr1' with integers from 1 to 5 another array 'arr2' with the same reversed. calculate the exponentiation of 'arr1' raised to the power of 'arr2' element-wise.
# ANSWER:-
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
result = np.power(arr1, arr2)
print(result)

[ 1 16 27 16  5]


In [ ]:
# Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
# ANSWER:-
def count_substring(arr, substring):
  return np.array([s.count(substring) for s in arr])

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
result = count_substring(arr, 'l')
print(result)

[2 1 2 0 2]


In [ ]:
# Write a function that extracts uppercase characters from a NumPy array of strings. arr = np.array(['Hello','World','OpenAI','GPT'])
# ANSWER:-
def extract_uppercase(arr):
  return np.array([''.join([c for c in s if c.isupper()]) for s in arr])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
result = extract_uppercase(arr)
print(result)

['H' 'W' 'OAI' 'GPT']


In [ ]:
# Write a function that replace occurrences of a substring in a NumPy arrayy of strings with a new string.
# ANSWER:-
def replace_substring(arr, old, new):
  return np.array([s.replace(old, new) for s in arr])
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result = replace_substring(arr, 'a', 'b')
print(result)

['bpple' 'bbnbnb' 'grbpe' 'pinebpple']


In [ ]:
# Write a function that concatenates strings in a NumPy array elements-wise.
# ANSWER:-
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
result = np.char.add(arr1, ' ')
result = np.char.add(result, arr2)
print(result)

['Hello Open' 'World AI']


In [ ]:
# Write a function that finds the length of the longest string in a NumPy array. arr = np.array(['apple','banana','grape','pineapple'])
# ANSWER:-
def longest_string(arr):
  lengths = np.array([len(s) for s in arr])
  return arr[np.argmax(lengths)]

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result = longest_string(arr)
print(result)

pineapple


In [ ]:
# Create a dataset of 100 random integers between 1 and 1000. compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
# ANSWER:-
data =  np.random.randint(1, 1001, size=100)
mean_val = np.mean(data)
median_val = np.median(data)
variance_val = np.var(data)
std_val = np.std(data)
print(mean_val)
print(median_val)
print(variance_val)
print(std_val)

513.92
513.5
82401.8336
287.0571956945166


In [ ]:
# Generate an array of 50 random numbers between 1 and 100. find the 25th and 75th percentiles of the dataset.
# ANSWER:-
data = np.random.randint(1, 101, size=50)
p25 = np.percentile(data, 25)
p75 = np.percentile(data, 75)
print(p25)
print(p75)

31.25
68.5


In [ ]:
# Create two arrays representing two sets of variables. compute the correlation coefficient between these arrays using NumPy's 'corrcoef' function.
# ANSWER:-
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 5, 4, 6])
correlation = np.corrcoef(arr1, arr2)[0, 1]
print(correlation)

0.8528028654224418


In [ ]:
# Create two matrices and perform matrix multiplication using NumPy's 'dot' function.
# ANSWER:-
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
result = np.dot(A, B)
print(result)

[[ 58  64]
 [139 154]]


In [ ]:
# Create an array of 50 integers between10 and 1000. calculate the 10th, 50th(median), and 90th percentiles along with th first and third quartiles.
# ANSWER:-
data = np.random.randint(10, 1001, size=50)
p10 = np.percentile(data, 10)
p50 = np.percentile(data, 50)
p90 = np.percentile(data, 90)
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)
print(p25)
print(q1)
print(q3)

31.25
273.75
674.25


In [ ]:
# Create a NumPy array of integers and find the index of a specific element.
# ANSWER:-
arr = np.array([10, 20, 30, 40, 50, 30, 60])
target = 30
indices = np.where(arr==target)
print(indices)

(array([2, 5]),)


In [ ]:
# Generate a random NumPy array and sort it in ascending order.
# ANSWER:-
arr = np.array([45, 23, 67, 12, 89, 34, 56])
sorted_arr = np.sort(arr)
print(sorted_arr)

[12 23 34 45 56 67 89]


In [ ]:
# Filter elements >20 in the given NumPy array.
# ANSWER:-
arr = np.array([12, 25, 6, 42, 8, 30])
filtered = arr[arr > 20]
print(filtered)

[25 42 30]


In [ ]:
# Filter elements which are divisible by 3 from a given NumPy array.
# ANSWER:-
arr = np.array([1, 5, 8, 12, 15])
filtered = arr[arr% 3 == 0]
print(filtered)

[12 15]


In [3]:
# filter elements which are >= 20 and <= 40 from a given NumPy array.
# ANSWER:-
arr = np.array([10, 20, 30, 40, 50])
filtered = arr[(arr >= 20) & (arr <= 40)]
print(filtered)

[20 30 40]


In [6]:
# For the given NumPy array, check its byte order using the 'dtype' attribute byteorder.
# ANSWER:-
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print(byte_order)

=


In [7]:
# For the given NumPy array, perform byte swapping in a place using 'byteswap()'.
# ANSWER:-
arr = np.array([1, 2, 3], dtype= np.int32)
arr_swapped = arr.byteswap(inplace=True)
print(arr_swapped)

[16777216 33554432 50331648]


In [11]:
# for the given NumPy array, swap its byte order without modifying the original array using 'newbyteorder()'.
# ANSWER:-
arr = np.array([1, 2, 3], dtype=np.int32)
swapped_new = arr.view(arr.dtype.newbyteorder())
print(swapped_new)

[16777216 33554432 50331648]


In [12]:
# For the given NumPy array and swap its byte order conditionally based on system endianness using 'newbyteorder'.
# ANSWER:-
arr = np.array([1, 2, 3], dtype=np.int32)
is_native = arr.dtype.byteorder == '='
if not is_native:
  arr = arr.view(arr.dtype.newbyteorder())
print(arr)

[1 2 3]


In [13]:
# For the given NumPy array, check if byte swapping is necessary for the current system using 'dtype' attribute 'byteorder'.
# ANSWER:-
arr = np.array([1, 2, 3], dtype=np.int32)
byteorder = arr.dtype.byteorder
needs_swap = (byteorder == '<' and np.dtype('int32').byteorder == '>')
print(needs_swap)

False


In [15]:
# Create a NumPy  array 'arr1' with values from 1 to 10. create a copy of 'arr1' named 'copy_arr' and modify an element in 'copy_arr'. check if modifying 'copy_arr' affects 'arr1'.
# ANSWER:-
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
copy_arr = arr1.copy()
copy_arr = 99
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
# Create 2D NumPy array 'matrix' of shape (3,3) with ramdoom integers. extract a slice 'view_slice' form the matrix. modify an element in 'view_slice' and obsserve if it changes the original matrix.
# ANSWER:-
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
view_slice = matrix[0:2, 0:2]
view_slice[0, 0]= 999
print(matrix[0, 0])

999


In [19]:
# Create a NumPy array 'array_a' of shape (4,3) with sequential integers from 1 to 12. Extract a slice 'view_b'from'array_a'and broadcast the addition of 5 to view_b.check if it alters the original 'array_a'.
# ANSWER:-
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[0:2, :]
view_b_modified = view_b+5
print(view_b_modified)

[[ 6  7  8]
 [ 9 10 11]]


In [20]:
# Create a NumPy array'orig_array' of shape(2,4) with values from 1 to 8. Create a reshaped view 'reshaped_view' of shape(4,2) from orig_array. modify an element in 'reshaped_view'and check if it reflects changes in the original'orig_array'.
# ANSWER:-
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4,2)
reshaped_view[0, 0] = 999
print(orig_array[0, 0])

999


In [21]:
# Create a NumPy  array 'data' of shape(3, 4) with random integers. Extract a copy 'data_copy' of elements greater than 5. modify an element in 'data_copy' and verify if it affects the original'data'.
# ANSWER:-
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
data_copy = data[data > 5].copy()
data_copy = 999
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
# Create two matrices A and B of identical shape conataining integers and perform addition and substraction operation between them.
# ANSWER:-
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])
addition = A+B
substraction = A-B
print(addition)
print(substraction)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]


In [23]:
# Generate two matrices 'C'(3*2) and 'D'(2*4) and perform matrix multiplication.
# ANSWER:-
C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])
result = np.dot(C, D)
print(result)

[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [25]:
# Create a matrix 'E' and find its transpose.
# ANSWER:-
E = np.array([[1, 2, 3], [4, 5, 6]])
E_transpose = E.T
print(E_transpose)

[[1 4]
 [2 5]
 [3 6]]


In [26]:
# Generate a square matrix 'F' and compute its determinant.
# ANSWER:-
F = np.array([[1, 2], [3, 4]])
det = np.linalg.det(F)
print(det)

-2.0000000000000004


In [27]:
# Create a square matrix 'G' and find its inverse.
# ANSWER:-
G = np.array([[1, 2], [3, 4]])
G_inverse = np.linalg.inv(G)
verification = np.dot(G, G_inverse)
print(verification)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
